modLoader="javafml"
loaderVersion="[35,)"
license="Not specified"

[[mods]]
modId="boss_tools"
version="4.4"
displayName="Space-Bosstools"
credits="Made by MrScautHD"
displayURL="https://www.curseforge.com/minecraft/mc-mods/space-bosstools"
logoFile="logo.png"
authors="MrScautHD"
description='''
Fly to Other Planets!
'''

[[dependencies.boss_tools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"


[[dependencies.boss_tools]]
    modId="obfuscate"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.boss_tools]]
    modId="obfuscate"
    mandatory=false
    ordering="NONE"
    side="BOTH"

